### ISSUE TITLE
fix(ci): pg types missing + 75 tests failing from 42003dc demo-stack commit

### ISSUE THREAD

**Issue by Kanevry** [Kanevry/aegis#111]
## Symptoms

Origin `main` since commit `42003dc feat: run aegis demo stack on local postgres` (2026-04-18 14:02 UTC):

### 1. Typecheck (blocks CI)

```
src/lib/postgres.ts(1,43): error TS7016: Could not find a declaration file for module 'pg'.
src/lib/postgres.ts(23,21): error TS7006: Parameter 'err' implicitly has an 'any' type.
```

`pg` 8.20.0 is a runtime dep but `@types/pg` is missing from `devDependencies`.

### 2. Test failures (75 tests across 6 files)

All from the new Postgres-backed services:
- `src/lib/approvals.test.ts`
- `src/lib/sessions.test.ts`
- `src/app/api/webhook/openclaw/dispatchers.test.ts`
- `src/app/api/approvals/route.test.ts`
- `src/app/api/sessions/[id]/route.test.ts`
- `tests/infra/docker-compose.test.ts`

These appear to be tests written against the old Supabase-backed implementations now pointing at Postgres stubs that don't behave the same way.

### 3. `@vitest/coverage-v8` missing (carried over from #108)

CI runs `pnpm test:coverage` but the package isn't in `devDependencies` / lockfile. Either install the coverage provider or switch CI to `pnpm test --run`.

## Fix scope

- [ ] Add `@types/pg` + `@vitest/coverage-v8` to devDependencies
- [ ] Rewrite failing tests against the new Postgres data path (or stub the pg pool properly)
- [ ] Confirm `docker-compose.yml` structural smoke test expectation matches the new shape (postgres init, DATABASE_URL wiring)

## Context

`pg` pool-based services (`src/lib/postgres.ts`, `src/lib/approvals.ts`, `src/lib/sessions.ts`) replaced the Supabase-client approach. Tests weren't migrated alongside the impl.

Surfaced during housekeeping session 2026-04-18 16:25. Supersedes the test-coverage half of #108.
